version: 2
updates:
  - package-ecosystem: npm
    directory: '/packages/react-scroll-section'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - EmaSuriano
    commit-message:
      prefix: 'fix'

  - package-ecosystem: npm
    directory: '/packages/demo'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - EmaSuriano
    commit-message:
      prefix: 'demo'
